### ISSUE TITLE
Subnet scanner > Unable to get mac address in target 33

### ISSUE THREAD

**Issue by andysagar** [TrueMLGPro/Wi-Fi_Info#52] opened 2023-10-18 07:56 UTC
I am unable to retrieve the MAC address from the IP, and the list of devices in the subnet scanner option is incomplete.

**Comment by TrueMLGPro** [comment] 2024-01-08 15:41
Hello, sorry for not responding in such a long time.

**This is not a bug**, Google has restricted access to this part of API for **non-system apps** (and devices without root access) targeting **targetSdk 32 and higher**.

**According to [Android Developers - MAC address availability changes in Android 11](https://developer.android.com/training/articles/user-data-ids#mac-11-plus), they have announced a change to the MAC address availability if you target Android 11 (or higher):**


> In addition, non-privileged apps can't access the device's MAC address; only network interfaces with an IP address are visible. This impacts the [`getifaddrs()`](https://android.googlesource.com/platform/bionic/+/master/libc/include/ifaddrs.h#83) and [`NetworkInterface.getHardwareAddress()`](https://developer.android.com/reference/java/net/NetworkInterface#getHardwareAddress()) methods, as well as sending `RTM_GETLINK` Netlink messages.
> 
> The following is a list of the ways that apps are affected by this change:
> 
> - `NetworkInterface.getHardwareAddress()` returns `null` for every interface.
> - Apps cannot use the `bind()` function on `NETLINK_ROUTE` sockets.
> - The `ip` command does not return information about interfaces.
> - Apps cannot send `RTM_GETLINK` messages.

I'm going to close this issue as I'm not currently aware of any possible fix or workaround for this behaviour.

**Comment by andysagar** [comment] 2024-01-08 15:42
I figured it out using API

**Closed** 2024-01-08 15:42 UTC
Labels: wontfix
