### ISSUE TITLE
Getting the error while importing in Android Studio - Could not get unknown property 'KEYSTORE_LOCATION' for SigningConfig$AgpDecorated_Decorated

### ISSUE THREAD

**Issue by 1210315127** [TrueMLGPro/Wi-Fi_Info#42] opened 2022-10-30 10:34 UTC
**Describe the bug**

Getting the error while importing in Android Studio. 
Build file 'C:\Users\Durga Prasad\AndroidStudioProjects\Wi_Fi_Info_DSCN\app\build.gradle' line: 9

A problem occurred evaluating project ':app'.
> Could not get unknown property 'KEYSTORE_LOCATION' for SigningConfig$AgpDecorated_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null} of type com.android.build.gradle.internal.dsl.SigningConfig$AgpDecorated.

**To Reproduce**
1. Go to Android Studio -> File -> Open -> Selected extracted zip file

2. Got error "Could not get unknown property 'KEYSTORE_LOCATION' for SigningConfig$AgpDecorated_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=pkcs12, v1SigningEnabled=true, v2SigningEnabled=true, enableV1Signing=null, enableV2Signing=null, enableV3Signing=null, enableV4Signing=null} of type com.android.build.gradle.internal.dsl.SigningConfig$AgpDecorated."

**Expected behavior**
Should run without error

**Comment by TrueMLGPro** [comment] 2022-10-30 12:13
Hello! The problem you're facing there is caused by the missing `gradle.properties` file in the project's root.
You need to create this file and declare these properties inside *(replacing the values too, if needed):*

![gradle.properties](https://user-images.githubusercontent.com/38999995/198877630-e8fe7ec6-40ab-47b5-89f6-971a999a14eb.png)

That will resolve this issue and you should be able to build the project without any problem now!

**Comment by TrueMLGPro** [comment] 2022-10-30 17:21
Oh, it seems like Gradle is trying to get an artifact of MagicButton from JCenter. I gotta update the package names in `build.gradle`. Please wait for an upcoming fix

**Comment by TrueMLGPro** [comment] 2022-11-02 17:24
Fixed it! Be sure to pull the latest commits!

**Comment by TrueMLGPro** [comment] 2022-11-03 06:43
Closing this

**Closed by TrueMLGPro** 2022-11-03 06:43 UTC
Labels: bug
